{% set name = "kinematics" %}
# {% set version = "0.2.7" %}
{% set data = load_setup_py_data() %}

package:
  name: "{{ name|lower }}"
  version: "{{ data['version'] }}"

source:
  path: ..

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python >=3.4
    - setuptools
    - numpy >=1.12
    - pytest-runner
  run:
    - python >=3.4
    - numpy >=1.12
test:
  imports:
    - kinematics
  requires:
    - pytest
    - pytest-cov
    - coverage

  commands:
    - pytest -vv --pyargs kinematics

about:
  home: https://github.com/skulumani/kinematics
  license: GNU General Public v3 (GPLv3)
  license_family: GPL3
  license_file: LICENSE
  summary: Python kinematics
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - skulumani
